exclude: 'build|stubs|k8s'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: trailing-whitespace
        - id: check-ast
        - id: check-merge-conflict
        - id: end-of-file-fixer
        - id: check-yaml
        - id: mixed-line-ending
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [
                # only error for syntax errors and undefined names
                "--select=E9,F63,F7,F82",
            ]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: README.md
        additional_dependencies: [toml]
        args: ["--profile", "black"]
