version: "3"
services:
  vlibras-translator-text-core:
    build: .
    image: vlibras_translator_core/text:2.2.0
    networks:
      - rabbitmq-net
    environment:
      AMQP_HOST: rabbitmq
      AMQP_PORT: 5672
      AMQP_USER: vlibras
      AMQP_PASS: vlibras
      AMQP_PREFETCH_COUNT: 1
      TRANSLATOR_QUEUE: "translate.to_text"
      ENABLE_DL_TRANSLATION: "false"
      HEALTHCHECK_PORT: 80
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management-alpine
    networks:
      - rabbitmq-net
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: vlibras
      RABBITMQ_DEFAULT_PASS: vlibras

networks:
  rabbitmq-net:

volumes:
  rabbitmq-data:
