apiVersion: extensions/v1beta1
#kubectl expose deployment translatorvideo --port=80 --type=LoadBalancer
kind: Deployment
metadata:
  name: translatorvideo
  labels:
    app: translatorvideo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translatorvideo
  template:
    metadata:
      labels:
        app: translatorvideo
    spec:
      containers:
        - image: vlibras/translator-video:04
          name: translatorvideo
          env:
            - name: AMQP_HOST
              value: "10.11.247.75"
            - name: AMQP_PORT
              value: "5672"
            - name: DB_HOST
              value: "10.0.27.166"
            - name: DB_PORT
              value: "27017"
          ports:
            - containerPort: 80
              name: vlibras-translator-video-port
          resources:
            requests:
              cpu: 600m
              memory: 1.5Gi
          #readinessProbe:
          #  httpGet:
          #    path: /healthcheck
          #    port: 80
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
      hostNetwork: true
