apiVersion: extensions/v1beta1
#kubectl expose deployment translatorvideo --port=80 --type=LoadBalancer
kind: Deployment
metadata:
  name: translatorvideo
  labels:
    app: translatorvideo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translatorvideow
  template:
    metadata:
      labels:
        app: translatorvideow
    spec:
      containers:
        - image: vlibras/translator-video:2.3.1
          name: translatorvideo
          env:
            - name: DB_HOST
              value: "10.0.27.166"
            - name: DB_PORT
              value: "27017"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "LOAO4aFTOM"
            - name: AMQP_USER
              value: "user"
            - name: AMQP_PASS
              value: "50inY8oprT"
            - name: AMQP_HOST
              value: "10.0.61.193"
            - name: AMQP_PORT
              value: "5672"
            - name: AMQP_PREFETCH_COUNT
              value: "1"
            - name: DB_NAME
              value: "vlibras-db"
            - name: DB_PORT
              value: "27017"
            - name: VLIBRAS_FILES
              value: "/video/translator/"
            - name: VIDEOMAKER_TMP_DIR
              value: "/video/translator/" 
            - name: VIDEOMAKER_BUNDLES_DIR
              value: "/video/bundles-mobile/"
            - name: VIDEOMAKER_QUEUE
              value: "translatevideo"
          stdin: true
          tty: true
          ports:
            - containerPort: 80
              name: tr-vid-port
          resources:
            requests:
              cpu: 1
              memory: 2.5Gi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 120
          volumeMounts:
            - name: video-nfs
              mountPath: /video/
      volumes:
        - name: video-nfs
          persistentVolumeClaim:
            claimName: nfs-volume
