apiVersion: extensions/v1beta1
#kubectl expose deployment translatorvideo --port=80 --type=LoadBalancer
kind: Deployment
metadata:
  name: translatorvideo
  labels:
    app: translatorvideo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translatorvideo
  template:
    metadata:
      labels:
        app: translatorvideo
    spec:
      containers:
        - image: vlibras/translator-video:1.0.6
          name: translatorvideo
          env:
            - name: AMQP_HOST
              value: "10.0.146.134"
            - name: AMQP_PORT
              value: "5672"
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: "10.0.27.166"
            - name: DB_PORT
              value: "27017"
            - name: VLIBRAS_FILES
              value: "/video/" 
          stdin: true
          tty: true
          ports:
            - containerPort: 80
              name: worker-video-pt
          resources:
            requests:
              cpu: 600m
              memory: 1.5Gi
          #readinessProbe:
          #  httpGet:
          #    path: /healthcheck
          #    port: 80
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
          volumeMounts:
            - name: video-nfs
              mountPath: /video/
      volumes:
        - name: video-nfs
          persistentVolumeClaim:
            claimName: nfs
      hostNetwork: true
