apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "tradcore.fullname" . }}-app-config'
  labels:
    {{ include "tradcore.labels" . | indent 4 }}
data:
{{ range $key, $val := .Values.tradcore.appConfig }}
  {{ $key | quote }}:  {{ $val | quote }}
{{- end }}